### PR TITLE
oidc provider: add oidc-policy option for oidc-issuer-url query param

### LINKED ISSUE #9: Microsoft Azure AD B2C Support
Hi,

I just came across this maintained fork of oauth2_proxy.

A while ago, we had created a small fork ourselves to include support Microsoft Azure AD B2C authentication.

This is different from the normal AAD provider, in that it's OIDC, however with an added parameter called policy to control different user journeys through login.

So we basically just added the policy option to the OIDC provider but with that we also needed a fork of the go-oidc package from CoreOS so this can pass the policy option to the auth endpoint.

Ideally, we'd want to contribute to this repo here and get the AAD B2C support into here, too.

I'm open for any ideas on how we can make this possible going forword, ideally without relying on forking another external package.

We might use the forked go-oidc package as basis for an own AAD B2C provider and include it here.

Thoughts on this?

This is our fork: https://github.com/karrieretutor/oauth2_proxy

Best regards
Marcel

### PR DESCRIPTION
**Pull request by ploxiln**
useful for Microsoft Azure AD B2C support
fixes #9

care to try this @marratj ? (though note that this fork does not have "huge cookie" support)

### CODE REVIEW

**Comment by marratj** [comment]
@ploxiln I see if I can try this, however it looks like we are pretty much dependent on the "huge cookie" support now, as passing the ID Token to the backend saves us from even further changing oauth2_proxy for custom claims we need in the backend.

So for now we will go with the pusher fork, where we look into even freely defining Auth & Redeem URLs instead of making them depend on the OIDC endpoint discovery process, which would make any special policy parameter implementation obsolete: https://github.com/pusher/oauth2_proxy/issues/27

What do you think, is there a possibility to inject this via context propagation like you did here, too? I didn't have real exposure to context in Go yet, so I'm not really sure what actually can be accomplished with it and what not...

**Comment by ploxiln** [comment]
Yeah, I think substituting an `http.Client` with a custom Transport just for this operation, which can return an arbitrary json response without even making a request, is probably better than forking `coreos/go-oidc`.

The go `context` is a rather general thing, it just happens that `coreos/go-oidc` offers this `ClientContext()` function to stash an `http.Client` which it will then look up and use.

**Comment by marratj** [comment]
Hmmm... I think I need to try if I can get it to work that way. Mind if I take your code from this PR as starting point?

**Comment by ploxiln** [comment]
Not at all, feel free.

**Comment by ploxiln** [comment]
by the way I moved around OIDC options processing a bit in #16

**Pull request closed without merging**
