### PR TITLE
Gitlab provider: Allow restriction by groups.

### PR DESCRIPTION
**Pull request by ploxiln**
rebase of https://github.com/bitly/oauth2_proxy/pull/637

### CODE REVIEW

**Comment by vishalg** [comment]
This seems to have broken the gitlab authentication. gitlab scope now defaults to api even when no groups are given in the configuration.

**Comment by ploxiln** [comment]
Thanks for the report. Might you be able to submit a pull request with the appropriate adjustment?

In the meantime, the v2.3 release should work as before regarding the gitlab provider.

**Comment by vishalg** [comment]
v2.3 works perfectly. I think the following fix in main.go should do the trick, it's a really small change and not sure if its worth a pull request

```diff
diff --git a/main.go b/main.go
index fb9b61c..cb720ac 100644
--- a/main.go
+++ b/main.go
@@ -22,6 +22,7 @@ func main() {
        upstreams := StringArray{}
        skipAuthRegex := StringArray{}
        googleGroups := StringArray{}
+       gitlabGroups := StringArray{}
 
        config := flagSet.String("config", "", "path to config file")
        showVersion := flagSet.Bool("version", false, "print version string")
@@ -48,7 +49,7 @@ func main() {
        flagSet.String("azure-tenant", "common", "go to a tenant-specific or common (tenant-independent) endpoint.")
        flagSet.String("github-org", "", "restrict logins to members of this organisation")
        flagSet.String("github-team", "", "restrict logins to members of this team")
-       flagSet.String("gitlab-group", "", "restrict logins to members of this group (full path) (may be given multiple times)")
+       flagSet.Var(&gitlabGroups, "gitlab-group", "restrict logins to members of this group (full path) (may be given multiple times)")
        flagSet.Var(&googleGroups, "google-group", "restrict logins to members of this google group (may be given multiple times).")
        flagSet.String("google-admin-email", "", "the google admin to impersonate for api calls")
        flagSet.String("google-service-account-json", "", "the path to the service account json credentials")
```

**Comment by ploxiln** [comment]
It is worth a pull request 😄 - I'll go ahead and open it, but I don't know the email address to put for you as the commit author.

**Comment by ploxiln** [comment]
(about the email address - I figured out I could use vishalg@users.noreply.github.com and it links to your github account)

**Comment by vishalg** [comment]
Great! Thanks for the credit.

**Pull request merged**
