### PR TITLE
Improve userInGroup to make it more efficient and able to search across nested groups

### PR DESCRIPTION
**Pull request by sneko**
I hope it will help others :)

### CODE REVIEW

**Comment by sneko** [comment]
Here an old related issue: https://github.com/bitly/oauth2_proxy/pull/358

@eskilandreen @snomann @framillien maybe you're still interested in :)

**Comment by ploxiln** [comment]
Very nice!
I'm going to squash-n-merge in order to tweak the commit title and message, I hope that's fine with you.

**Comment by sneko** [comment]
Sure go ahead! :)

**Comment by sneko** [comment]
@ploxiln just to follow up:

There is an issue with members that are outside the group domain (means a bug with @gmail.com in a @domain.com group).

I just discovered that. That's something on Google side but I can't figure out if this is the wanted behavior... It seems so strange.

For now they didn't answer to the issue someone has posted: https://issuetracker.google.com/issues/109861216

I will keep you updated. If they don't fix the bug I think we have to forget about using subgroups and get back to the old loops over group members 😢 

EDIT: a possible way with the old way before this PR would be to set to true the "includeDerivedMembership" (https://developers.google.com/admin-sdk/directory/v1/reference/members/list). But I guess the pagination limit would be present.

**Pull request merged**
